var menuMap = {
  "/editorWorkspace":"ContentCore.EditWorkSpace",
  "/catalogIndex":"ContentCore.Catalog",
  "/settings":"MainMenus.AdminWorkspace",
  "/settings/site":"ContentCore.SiteMenu",
  '/settings/catalog': 'ContentCore.Catalog',
  "/settings/template":"ContentCore.TemplateMenu",
  "/settings/specialTemplate":"Pageweaver.TemplateMenu",
  "/settings/tag":"ContentCore.TagMenu",
  "/settings/file":"ContentCore.FileMenu",
  "/settings/dimens":"DimensionManage",
  "/settings/indexes":"ContentCore.IndexMenu",
  "/settings/dicManager":"Search.DicManager",
  "/settings/weightsConfig":"Search.WeightsConfig",
  "/settings/workflow":"Admin.Workflow",
  "/settings/extendModel":"ContentCore.ExtendModelMenu",
  "/settings/assessCatalog":"ContentAssess.AssessmentManage",
  "/settings/word":"WordManage",
  "/plugins":"MainMenus.Modules",
  "/plugins/imageplayer":"ImagePlayerManage",
  "/plugins/weixin":"Weixin.Manage",
  "/plugins/vote":"VoteManage",
  "/plugins/advertise":"AdvertiseManage",
  "/plugins/browsepriv":"BrowsePrivGroupManage",
  "/plugins/comment":"CommentManage",
  "/plugins/face":"CommentFaceManage",
  "/plugins/customForm":"Modules.CustomForm",
  "/plugins/links":"LinkManage",
  "/plugins/messageboard":"MessageBoardManage",
  "/plugins/sitestyle":"SiteStyleManage",
  "/member":"MainMenus.MemberManager",
  "/member/info":"Member.Information",
  "/member/branch":"Member.Branch",
  "/member/role":"Member.Role",
  "/member/level":"Member.Level",
  "/member/scoreOperateList":"Member.ScoreOperation",
  // "/member/memberMenu":"Member.Menu",
  "/member/messageManager":"Message.MessageManager",
  "/member/messageTemplate":"Message.Template",
  "/stat":"MainMenus.Stat",
  "/datachannel":"MainMenus.DataChannel",
  "/datachannel/outerData":"Gather.OuterData",
  "/datachannel/fromWeb":"DataChannel.WebGather",
  "/datachannel/publishPoint":"ContentAdvance.PublishPoint",
  "/datachannel/publishPlatform":"ContentCore.PublishPlatform",
  "/datachannel/fromDB":"DataChannel.DataBaseGather",
  "/datachannel/deploy":"SiteGroup.Deploy",
  "/datachannel/gather":"SiteGroup.Gather",
  "/datachannel/catalogMapping":"Workspace.CatalogMapping",
  "/platform":"Platform.System",
  "/platform/systemInfo":"Platform.SystemInfo",
  "/platform/detector":"Platform.Detector",
  "/platform/branch":"Platform.Branch",
  "/platform/role":"Platform.Role",
  "/platform/user":"Platform.User",
  "/platform/security":"Platform.AccountSecurity",
  "/platform/code":"Platform.Code",
  "/platform/config":"Platform.Config",
  "/platform/metadata":"Platform.Metadata",
  "/platform/schedule":"Platform.Schedule",
  "/platform/menu":"Platform.Menu",
  "/platform/plugin":"Platform.Plugin",
  "/platform/backup":"Platform.Backup",
  "/platform/log":"Platform.Log",
  "/platform/api":"Platform.API",
  "/workspace":"Workspace.Draft",
  "/workspace/person":"Draft.Person",
  "/workspace/dept":"Draft.Dept",
  "/socialmedia":"MainMenus.SocialMedia",
  "/socialmedia/accounts":"SocialMedia.MediaAccount",
  "/socialmedia/mediaConfigList":"SocialMedia.MediaConfig",
  "/socialmedia/accountType":"SocialMedia.AccountType",
  "/socialmedia/mediaConditionList":"SocialMedia.MediaCondition",
  "/socialmedia/mediaPush":"SocialMedia.MediaPush",
  "/socialmedia/commentsList":"SocialMedia.CommentManage",
  "/socialmedia/fansAccountList":"SocialMedia.FansManage",
  "/socialmedia/weiboMegTab":"SocialMedia.WeiBoManage",
  "/socialmedia/weixinList":"Weixin.Manage",
  /**暂时屏蔽app和小程序的权限 */
  // "/socialmedia/appManage":"Platform.Menu",
  // "/socialmedia/miniAppManage":"Platform.Menu",
}

export default menuMap
